version: "3.8"

services:
  mysql:
    image: mysql:5.7.43
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /opt/wx_mall/mysql/data:/var/lib/mysql
    network_mode: "host"
